# Generated by Django 4.2.27 on 2026-08-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(max_length=500)),
                ("type", models.CharField(max_length=60)),
            ],
            options={
                "ordering": ["-time"],
            },
        ),
        migrations.CreateModel(
            name="PlantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_name", models.CharField(max_length=120, verbose_name="nom")),
                ("humidity_min", models.IntegerField(verbose_name="humidité min. (%)")),
                ("humidity_max", models.IntegerField(verbose_name="humidité max. (%)")),
                ("temperature_min", models.FloatField(verbose_name="temp. min. (°C)")),
                ("temperature_max", models.FloatField(verbose_name="temp. max. (°C)")),
                (
                    "luminosity_per_day",
                    models.IntegerField(verbose_name="luminosité / jour (h)"),
                ),
                (
                    "harvest_days",
                    models.IntegerField(verbose_name="jours avant récolte"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="plant_types/", verbose_name="photo"
                    ),
                ),
            ],
            options={
                "ordering": ["plant_name"],
            },
        ),
        migrations.CreateModel(
            name="GrowingPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=120, verbose_name="nom affiché"),
                ),
                (
                    "planted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de plantation"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("harvested", models.BooleanField(default=False)),
                (
                    "last_watering",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernier arrosage"
                    ),
                ),
                (
                    "growing_state",
                    models.IntegerField(default=0, verbose_name="avancement (%)"),
                ),
                (
                    "current_temperature",
                    models.FloatField(
                        blank=True, null=True, verbose_name="température actuelle"
                    ),
                ),
                (
                    "current_humidity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="humidité actuelle"
                    ),
                ),
                (
                    "current_luminosity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="luminosité actuelle"
                    ),
                ),
                (
                    "plant_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growing_plants",
                        to="plant_management.planttype",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
    ]
