# Generated by Django 4.2.27 on 2026-08-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="growingplant",
            name="auto_luminosity",
            field=models.BooleanField(default=True, verbose_name="lumière automatique"),
        ),
        migrations.AlterField(
            model_name="growingplant",
            name="display_name",
            field=models.CharField(max_length=120, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="growingplant",
            name="harvested",
            field=models.BooleanField(default=False, verbose_name="récoltée"),
        ),
        migrations.AlterField(
            model_name="growingplant",
            name="plant_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="growing_plants",
                to="plant_management.planttype",
                verbose_name="type de plante",
            ),
        ),
        migrations.AlterField(
            model_name="growingplant",
            name="planted_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="planté le"),
        ),
    ]
