# Generated by Django 4.2.27 on 2026-08-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0002_growingplant_auto_luminosity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="growingplant",
            name="harvest_day",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="récoltée le"
            ),
        ),
    ]
