# Generated by Django 4.2.27 on 2026-08-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0003_growingplant_harvest_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growingplant",
            name="auto_luminosity",
            field=models.BooleanField(
                default=False, verbose_name="lumière automatique"
            ),
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nom")),
                ("model", models.CharField(max_length=120, verbose_name="modèle")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "mqtt_topic",
                    models.CharField(max_length=200, verbose_name="topic MQTT"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="sensors/", verbose_name="photo"
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensors",
                        to="plant_management.growingplant",
                        verbose_name="assigné à",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
