# Generated by Django 4.2.27 on 2026-08-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0005_sensordata"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="humidity_payload_label",
            field=models.CharField(
                blank=True,
                default="humidity",
                max_length=120,
                verbose_name="humidité (clé du payload)",
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="luminosity_payload_label",
            field=models.CharField(
                blank=True,
                default="luminosity",
                max_length=120,
                verbose_name="luminosité (clé du payload)",
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="temperature_payload_label",
            field=models.CharField(
                blank=True,
                default="temperature",
                max_length=120,
                verbose_name="température (clé du payload)",
            ),
        ),
    ]
