# Generated by Django 4.2.27 on 2026-08-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0006_sensor_humidity_payload_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growingplant",
            name="current_luminosity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="intensité lumineuse (%)"
            ),
        ),
    ]
