# Generated by Django 4.2.27 on 2026-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0007_alter_growingplant_current_luminosity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growingplant",
            name="current_luminosity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="niveau de lumière"
            ),
        ),
    ]
