# Generated by Django 4.2.27 on 2026-08-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0008_alter_growingplant_current_luminosity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actionner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nom")),
                ("is_on", models.BooleanField(default=False, verbose_name="allumé")),
                (
                    "last_switch",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernier changement"
                    ),
                ),
                (
                    "mqtt_topic",
                    models.CharField(max_length=200, verbose_name="topic MQTT"),
                ),
                (
                    "act_on",
                    models.CharField(
                        choices=[
                            ("humidity", "humidité"),
                            ("luminosity", "lumière"),
                            ("temperature", "température"),
                        ],
                        default="humidity",
                        max_length=60,
                        verbose_name="agit sur",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="actionners/", verbose_name="photo"
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actionners",
                        to="plant_management.growingplant",
                        verbose_name="assigné à",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
