# Generated by Django 4.2.27 on 2026-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0009_actionner"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionner",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
