# Generated by Django 4.2.27 on 2026-08-21 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0010_actionner_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planttype",
            name="luminosity_per_day",
        ),
        migrations.AddField(
            model_name="planttype",
            name="light_ends_at",
            field=models.TimeField(
                default=datetime.time(20, 0), verbose_name="lumière jusqu'à"
            ),
        ),
        migrations.AddField(
            model_name="planttype",
            name="light_starts_at",
            field=models.TimeField(
                default=datetime.time(8, 0), verbose_name="lumière à partir de"
            ),
        ),
    ]
