# Generated by Django 4.2.27 on 2026-08-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0011_remove_planttype_luminosity_per_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="growingplant",
            name="auto_watering",
            field=models.BooleanField(
                default=False, verbose_name="arrosage automatique"
            ),
        ),
    ]
