# Generated by Django 4.2.27 on 2026-08-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0013_actionner_topics_in_and_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="battery_level",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="batterie (%)"
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="battery_payload_label",
            field=models.CharField(
                blank=True,
                default="battery",
                max_length=120,
                verbose_name="batterie (clé du payload)",
            ),
        ),
    ]
