# Generated by Django 4.2.27 on 2026-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0014_sensor_battery_level_sensor_battery_payload_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nom")),
                (
                    "stream_url",
                    models.CharField(max_length=300, verbose_name="adresse du flux"),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
