# Generated by Django 4.2.27 on 2026-09-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plant_management", "0015_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cameras",
                to="plant_management.growingplant",
                verbose_name="assigné à",
            ),
        ),
    ]
